<?
// $Id$

# Copyright (c) 2010 Impressive.media
# Author: Eugen Mayer
/**
 * Implementation of hook_help().
 */

function revision_branching_menu() {
  $items = array();
  $items["node/%revision_branching_vid/revedit"] = array(
    'title' => 'Edit',
    'page callback' => '_content_moderation_node_edit_page',
    'page arguments' => array(1),
    'access callback' => 'node_access',
    'access arguments' => array('update', 1),
    'weight' => 1,
    'file' => 'node.pages.inc',
    'file path' => drupal_get_path('module', 'node'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/*
 * Implementation of hook_help
 */
function revision_branching_help($path, $arg) {
  switch ($path) {
    case 'admin/help#revision_branching':
      return '<p>'. t("Enables you to edit revisions and therefor branch of. So new revisions are based on some specific revision") .'</p>';
  }
}

function revision_branching_vid_load($vid) {
  $nid = _content_moderation_get_nid($vid);
  return node_load($nid,$vid);
}

/*
 * Implementation of hook_nodeapi
 */
function revision_branching_nodeapi(&$node, $op, $a3, $a4) {
  global $user;
  $type = $node->type;
  if (!_content_moderation_moderate_node_type($type)) {
    // Dont moderate this content type
    return;
  }
  //dsm($op);
  switch ($op) {
    case 'presave':
      break;
    case 'insert':
      break;
    case 'update':
      break;
    case 'view':
      break;
  }
}
